Global_settings:
  main:
    meta_keywords: Dakota cms, дакота cms,  PHP, Ajax, JavaScript, , MySQL, CSS, (x)HTML, XML,  GUI
    meta_description: Новый сайт на Dakota CMS
    title: Новый сайт на Dakota CMS
    template: default
